export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SHOW_LOADING_MODAL = 'SHOW_LOADING_MODAL';
export const HIDE_LOADING_MODAL = 'HIDE_LOADING_MODAL';
//产品相关
export const SAVE_PRODUCTS_INFO = 'SAVE_PRODUCTS_INFO';
//控制是否刷新一个页面
export const REFRESH_PAGE = 'REFRESH_PAGE';
//缓存常量
export const TOKEN = 'TOKEN';
export const USER = 'USER';
export const LOCALE = 'LOCALE';
export const LOCALEID = 'LOCALEID';
export const CURRENCY = 'CURRENCY';

export const REQUEST_PRODUCT_CATEGORY = 'REQUEST_PRODUCT_CATEGORY';
export const CHANGE_PRODUCT_CATEGORY = 'CHANGE_PRODUCT_CATEGORY';
export const CHANGE_PRODUCT_CATEGORY_LOADING =
  'CHANGE_PRODUCT_CATEGORY_LOADING';
export const CHANGE_PRODUCT_LIST = 'CHANGE_PRODUCT_LIST';
export const CHANGE_PRODUCT_DETAIL = 'CHANGE_PRODUCT_DETAIL';
export const CHANGE_PRODUCT_LOADING = 'CHANGE_PRODUCT_LOADING';
export const CHANGE_CART_LOADING = 'CHANGE_CART_LOADING';
export const CHANGE_CART_LIST = 'CHANGE_CART_LIST';
export const CLEAR_CART_LIST = 'CLEAR_CART_LIST';
export const CHANGE_ORDER_ADDRESS = 'CHANGE_ORDER_ADDRESS';
export const CHANGE_ORDER_PAYMENT = 'CHANGE_ORDER_PAYMENT';
export const CHANGE_ORDER_DELIVERY = 'CHANGE_ORDER_DELIVERY';
export const CHANGE_ORDER_SELECTED_ADDRESS = 'CHANGE_ORDER_SELECTED_ADDRESS';
export const CHANGE_ORDER_CART_INFO = 'CHANGE_ORDER_CART_INFO';

export const CHANGE_COUPONS_LIST_LOADING = 'CHANGE_COUPONS_LIST_LOADING';
export const CHANGE_COUPONS_LIST = 'CHANGE_COUPONS_LIST';

export const CHANGE_FROUM_CATEGORY = 'CHANGE_FROUM_CATEGORY';
export const CHANGE_FROUM_CATEGORY_LOADING = 'CHANGE_FROUM_CATEGORY_LOADING';

export const CHANGE_FROUM_POST = 'CHANGE_FROUM_POST';
export const CHANGE_FROUM_POST_LOADING = 'CHANGE_FROUM_POST_LOADING';

export const CHANGE_POST_DETAIL = 'CHANGE_POST_DETAIL';
export const CHANGE_POST_DETAIL_LOADING = 'CHANGE_POST_DETAIL_LOADING';

export const REQUEST_HOMEPRODUCT = 'REQUEST_HOMEPRODUCT';
export const CHANGE_HOMEPRODUCT = 'CHANGE_HOMEPRODUCT';
export const CHANGE_HOMEPRODUCT_LOADING = 'CHANGE_HOMEPRODUCT_LOADING';

export const CHANGE_WISH_LIST = 'CHANGE_WISH_LIST';
export const CHANGE_WISH_LIST_LOADING = 'CHANGE_WISH_LIST_LOADING';

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_CURRENCY_LOADING = 'CHANGE_CURRENCY_LOADING';
